"""Server-issued confirmation tokens for write operations.

WHY THIS EXISTS
---------------
`update_ticket` used to gate commits behind a `confirm: bool` parameter set by
the caller. That is not a gate. A boolean the caller supplies is caller policy
wearing a parameter's clothes: any model that wanted to skip the preview passed
`confirm=true` on the first call and committed immediately, and the tool
description asking it not to was a request — exactly the thing this repo exists
to argue against. The reviewer who found it was right, and it was the last claim
in the README that the code did not back.

A token fixes the part a tool actually can fix. It is minted by the server
during a dry run and cannot be constructed by the caller, so the commit path is
unreachable without first producing a preview.

WHAT A TOKEN PROVES, AND WHAT IT DOES NOT
-----------------------------------------
It proves:

  - a preview was generated by this server, for this ticket;
  - the change now being committed is byte-identical to the change that was
    previewed — swapping fields between preview and commit invalidates it;
  - the ticket has not moved since the preview, so the before/after the user was
    shown still describes reality;
  - the token has not been used before, and is not stale.

It does NOT prove a human read the preview. No tool can establish that on its
own; that is what the elicitation path in `server.py` is for, where the client
supports it. Claiming otherwise would repeat the mistake this module fixes.

DESIGN NOTES
------------
The binding is a SHA-256 over (ticket_id, ordered change set, ticket version).
The token is a random opaque string; the digest is stored beside it rather than
encoded into it, so nothing about the pending change travels through the model's
context and a caller cannot mint one by reproducing the hash input.

Rejections are typed. "Expired" and "the ticket changed under you" call for
different recovery, and a caller that cannot tell them apart will retry the
wrong one.

Clock is injectable. Tests that sleep are tests that flake.
"""

from __future__ import annotations

import hashlib
import json
import secrets
import time
from collections.abc import Callable
from dataclasses import dataclass
from enum import Enum

DEFAULT_TTL_SECONDS = 300.0
"""Five minutes. Long enough for a human to read a preview and answer, short
enough that an abandoned preview cannot authorise a commit into a queue that has
moved on."""


class Rejection(str, Enum):
    """Why a token was refused. Each implies a different recovery."""

    UNKNOWN = "unknown"
    """No such token. Either fabricated or already consumed. Re-run the dry run."""

    EXPIRED = "expired"
    """Issued too long ago. The preview is stale; produce a fresh one."""

    CHANGE_MISMATCH = "change_mismatch"
    """The token was issued for a different change set or a different ticket.
    This is the interesting rejection: it is what stops a preview of one edit
    being used to commit another."""

    TICKET_MOVED = "ticket_moved"
    """The ticket was modified after the preview was issued, so the before/after
    the user approved no longer describes the ticket. Re-preview against current
    state."""


@dataclass(frozen=True)
class Validation:
    ok: bool
    rejection: Rejection | None = None
    message: str = ""


@dataclass
class _Pending:
    digest: str
    issued_at: float


def fingerprint(ticket_id: str, changes: list[tuple[str, object, object]], version: str) -> str:
    """Stable digest of exactly what was previewed.

    `changes` is (field, before, after) triples. Order is normalised so that two
    logically identical previews agree, but the values themselves are not — a
    preview of `status: open -> pending` must not validate a commit of
    `status: open -> resolved`.
    """
    payload = json.dumps(
        {
            "ticket_id": ticket_id,
            "version": version,
            "changes": sorted(
                ([str(f), repr(b), repr(a)] for f, b, a in changes),
                key=lambda triple: triple[0],
            ),
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def ticket_version(ticket: dict) -> str:
    """A cheap optimistic-concurrency stamp for a ticket's mutable state.

    Covers the fields `update_ticket` can change, plus the note trail. Not a
    general-purpose ETag: it deliberately ignores immutable fields, so an
    unrelated rewrite of the ticket body does not invalidate a pending preview.
    """
    payload = json.dumps(
        {
            "status": ticket.get("status"),
            "tier": ticket.get("tier"),
            "priority": ticket.get("priority"),
            "assignee": ticket.get("assignee"),
            "notes": len(ticket.get("notes") or []),
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]


class ConfirmationStore:
    """Pending previews, in memory for the process lifetime.

    In-process is the right scope for a stdio server: one client, one session,
    and a token that outlived the process would be authorising a commit against
    a ticket store that no longer exists. A hosted deployment would need shared
    storage, which is a different problem than the one this demonstrates.
    """

    def __init__(
        self,
        ttl_seconds: float = DEFAULT_TTL_SECONDS,
        clock: Callable[[], float] = time.monotonic,
    ):
        self._ttl = ttl_seconds
        self._clock = clock
        self._pending: dict[str, _Pending] = {}

    def issue(
        self, ticket_id: str, changes: list[tuple[str, object, object]], version: str
    ) -> str:
        """Mint a token for a previewed change. Called only on the dry-run path."""
        self._evict_expired()
        token = f"chg_{secrets.token_urlsafe(24)}"
        self._pending[token] = _Pending(
            digest=fingerprint(ticket_id, changes, version), issued_at=self._clock()
        )
        return token

    def redeem(
        self,
        token: str,
        ticket_id: str,
        changes: list[tuple[str, object, object]],
        version: str,
        current_version: str,
    ) -> Validation:
        """Validate and consume a token.

        A token is consumed on any outcome that identifies it as genuine —
        including a mismatch — so that a caller cannot probe a single token
        against different change sets until one sticks.

        Deliberately does NOT sweep expired tokens first. Doing so deletes the
        very token being redeemed and reports EXPIRED as UNKNOWN, collapsing two
        rejections that call for different recovery — "your preview went stale,
        make a fresh one" versus "that token never existed". Housekeeping belongs
        on the issue path, where nothing is looking anything up.
        """
        pending = self._pending.get(token)
        if pending is None:
            return Validation(
                ok=False,
                rejection=Rejection.UNKNOWN,
                message=(
                    "No pending change matches that confirmation_token. It was never "
                    "issued, has already been used, or has expired. Call update_ticket "
                    "again without confirmation_token to produce a fresh preview."
                ),
            )

        if self._clock() - pending.issued_at > self._ttl:
            del self._pending[token]
            return Validation(
                ok=False,
                rejection=Rejection.EXPIRED,
                message=(
                    f"That preview is older than {int(self._ttl)}s and has expired. "
                    "Re-run the dry run and show the user a current preview."
                ),
            )

        if version != current_version:
            del self._pending[token]
            return Validation(
                ok=False,
                rejection=Rejection.TICKET_MOVED,
                message=(
                    "The ticket changed after that preview was generated, so the "
                    "before/after values the user approved no longer describe it. "
                    "Re-run the dry run against current state and confirm again."
                ),
            )

        expected = fingerprint(ticket_id, changes, version)
        del self._pending[token]
        if pending.digest != expected:
            return Validation(
                ok=False,
                rejection=Rejection.CHANGE_MISMATCH,
                message=(
                    "That confirmation_token was issued for a different change. A "
                    "token authorises exactly the edit that was previewed — it cannot "
                    "be carried over to another ticket, field, or value. Preview this "
                    "change and confirm it on its own."
                ),
            )

        return Validation(ok=True)

    def _evict_expired(self) -> None:
        now = self._clock()
        for token in [t for t, p in self._pending.items() if now - p.issued_at > self._ttl]:
            del self._pending[token]

    def __len__(self) -> int:  # pragma: no cover - diagnostics
        return len(self._pending)
